PREFIX : <http://www.w3.org>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?V11 ?V12 ?V13 ?V14 ?V21 ?V22 ?V23 ?V24 ?V31 ?V32 ?V33 ?V34 ?V41 ?V42 ?V43 ?V44
WHERE {
	:D1 :values ?V11.
	:D1 :values ?V12.
	:D1 :values ?V13.
	:D1 :values ?V14.
	:D1 :values ?V21.
	:D1 :values ?V22.
	:D1 :values ?V23.
	:D1 :values ?V24.
	:D1 :values ?V31.
	:D1 :values ?V32.
	:D1 :values ?V33.
	:D1 :values ?V34.
	:D1 :values ?V41.
	:D1 :values ?V42.
	:D1 :values ?V43.
	:D1 :values ?V44.
	FILTER (
		( (?V11 != 1 || ?V12 != 1) && (?V11 != 2 || ?V12 != 2) && (?V11 != 3 || ?V12 != 3) && (?V11 != 4 || ?V12 != 4) )
		&& 
		( (?V11 != 1 || ?V13 != 1) && (?V11 != 2 || ?V13 != 2) && (?V11 != 3 || ?V13 != 3) && (?V11 != 4 || ?V13 != 4) )
		&& 
		( (?V11 != 1 || ?V14 != 1) && (?V11 != 2 || ?V14 != 2) && (?V11 != 3 || ?V14 != 3) && (?V11 != 4 || ?V14 != 4) )
		&& 
		( (?V11 != 1 || ?V21 != 1) && (?V11 != 2 || ?V21 != 2) && (?V11 != 3 || ?V21 != 3) && (?V11 != 4 || ?V21 != 4) )
		&& 
		( (?V11 != 1 || ?V31 != 1) && (?V11 != 2 || ?V31 != 2) && (?V11 != 3 || ?V31 != 3) && (?V11 != 4 || ?V31 != 4) )
		&& 
		( (?V11 != 1 || ?V41 != 1) && (?V11 != 2 || ?V41 != 2) && (?V11 != 3 || ?V41 != 3) && (?V11 != 4 || ?V41 != 4) )
		&& 
		( (?V11 != 1 || ?V22 != 1) && (?V11 != 2 || ?V22 != 2) && (?V11 != 3 || ?V22 != 3) && (?V11 != 4 || ?V22 != 4) )
		&& 
		( (?V12 != 1 || ?V13 != 1) && (?V12 != 2 || ?V13 != 2) && (?V12 != 3 || ?V13 != 3) && (?V12 != 4 || ?V13 != 4) )
		&& 
		( (?V12 != 1 || ?V14 != 1) && (?V12 != 2 || ?V14 != 2) && (?V12 != 3 || ?V14 != 3) && (?V12 != 4 || ?V14 != 4) )
		&& 
		( (?V12 != 1 || ?V22 != 1) && (?V12 != 2 || ?V22 != 2) && (?V12 != 3 || ?V22 != 3) && (?V12 != 4 || ?V22 != 4) )
		&& 
		( (?V12 != 1 || ?V32 != 1) && (?V12 != 2 || ?V32 != 2) && (?V12 != 3 || ?V32 != 3) && (?V12 != 4 || ?V32 != 4) )
		&& 
		( (?V12 != 1 || ?V42 != 1) && (?V12 != 2 || ?V42 != 2) && (?V12 != 3 || ?V42 != 3) && (?V12 != 4 || ?V42 != 4) )
		&& 
		( (?V12 != 1 || ?V21 != 1) && (?V12 != 2 || ?V21 != 2) && (?V12 != 3 || ?V21 != 3) && (?V12 != 4 || ?V21 != 4) )
		&& 
		( (?V13 != 1 || ?V14 != 1) && (?V13 != 2 || ?V14 != 2) && (?V13 != 3 || ?V14 != 3) && (?V13 != 4 || ?V14 != 4) )
		&& 
		( (?V13 != 1 || ?V23 != 1) && (?V13 != 2 || ?V23 != 2) && (?V13 != 3 || ?V23 != 3) && (?V13 != 4 || ?V23 != 4) )
		&& 
		( (?V13 != 1 || ?V33 != 1) && (?V13 != 2 || ?V33 != 2) && (?V13 != 3 || ?V33 != 3) && (?V13 != 4 || ?V33 != 4) )
		&& 
		( (?V13 != 1 || ?V43 != 1) && (?V13 != 2 || ?V43 != 2) && (?V13 != 3 || ?V43 != 3) && (?V13 != 4 || ?V43 != 4) )
		&& 
		( (?V13 != 1 || ?V24 != 1) && (?V13 != 2 || ?V24 != 2) && (?V13 != 3 || ?V24 != 3) && (?V13 != 4 || ?V24 != 4) )
		&& 
		( (?V14 != 1 || ?V24 != 1) && (?V14 != 2 || ?V24 != 2) && (?V14 != 3 || ?V24 != 3) && (?V14 != 4 || ?V24 != 4) )
		&& 
		( (?V14 != 1 || ?V34 != 1) && (?V14 != 2 || ?V34 != 2) && (?V14 != 3 || ?V34 != 3) && (?V14 != 4 || ?V34 != 4) )
		&& 
		( (?V14 != 1 || ?V44 != 1) && (?V14 != 2 || ?V44 != 2) && (?V14 != 3 || ?V44 != 3) && (?V14 != 4 || ?V44 != 4) )
		&& 
		( (?V14 != 1 || ?V23 != 1) && (?V14 != 2 || ?V23 != 2) && (?V14 != 3 || ?V23 != 3) && (?V14 != 4 || ?V23 != 4) )
		&& 
		( (?V21 != 1 || ?V22 != 1) && (?V21 != 2 || ?V22 != 2) && (?V21 != 3 || ?V22 != 3) && (?V21 != 4 || ?V22 != 4) )
		&& 
		( (?V21 != 1 || ?V23 != 1) && (?V21 != 2 || ?V23 != 2) && (?V21 != 3 || ?V23 != 3) && (?V21 != 4 || ?V23 != 4) )
		&& 
		( (?V21 != 1 || ?V24 != 1) && (?V21 != 2 || ?V24 != 2) && (?V21 != 3 || ?V24 != 3) && (?V21 != 4 || ?V24 != 4) )
		&& 
		( (?V21 != 1 || ?V31 != 1) && (?V21 != 2 || ?V31 != 2) && (?V21 != 3 || ?V31 != 3) && (?V21 != 4 || ?V31 != 4) )
		&& 
		( (?V21 != 1 || ?V41 != 1) && (?V21 != 2 || ?V41 != 2) && (?V21 != 3 || ?V41 != 3) && (?V21 != 4 || ?V41 != 4) )
		&& 
		( (?V22 != 1 || ?V23 != 1) && (?V22 != 2 || ?V23 != 2) && (?V22 != 3 || ?V23 != 3) && (?V22 != 4 || ?V23 != 4) )
		&& 
		( (?V22 != 1 || ?V24 != 1) && (?V22 != 2 || ?V24 != 2) && (?V22 != 3 || ?V24 != 3) && (?V22 != 4 || ?V24 != 4) )
		&& 
		( (?V22 != 1 || ?V32 != 1) && (?V22 != 2 || ?V32 != 2) && (?V22 != 3 || ?V32 != 3) && (?V22 != 4 || ?V32 != 4) )
		&& 
		( (?V22 != 1 || ?V42 != 1) && (?V22 != 2 || ?V42 != 2) && (?V22 != 3 || ?V42 != 3) && (?V22 != 4 || ?V42 != 4) )
		&& 
		( (?V23 != 1 || ?V24 != 1) && (?V23 != 2 || ?V24 != 2) && (?V23 != 3 || ?V24 != 3) && (?V23 != 4 || ?V24 != 4) )
		&& 
		( (?V23 != 1 || ?V33 != 1) && (?V23 != 2 || ?V33 != 2) && (?V23 != 3 || ?V33 != 3) && (?V23 != 4 || ?V33 != 4) )
		&& 
		( (?V23 != 1 || ?V43 != 1) && (?V23 != 2 || ?V43 != 2) && (?V23 != 3 || ?V43 != 3) && (?V23 != 4 || ?V43 != 4) )
		&& 
		( (?V24 != 1 || ?V34 != 1) && (?V24 != 2 || ?V34 != 2) && (?V24 != 3 || ?V34 != 3) && (?V24 != 4 || ?V34 != 4) )
		&& 
		( (?V24 != 1 || ?V44 != 1) && (?V24 != 2 || ?V44 != 2) && (?V24 != 3 || ?V44 != 3) && (?V24 != 4 || ?V44 != 4) )
		&& 
		( (?V31 != 1 || ?V32 != 1) && (?V31 != 2 || ?V32 != 2) && (?V31 != 3 || ?V32 != 3) && (?V31 != 4 || ?V32 != 4) )
		&& 
		( (?V31 != 1 || ?V33 != 1) && (?V31 != 2 || ?V33 != 2) && (?V31 != 3 || ?V33 != 3) && (?V31 != 4 || ?V33 != 4) )
		&& 
		( (?V31 != 1 || ?V34 != 1) && (?V31 != 2 || ?V34 != 2) && (?V31 != 3 || ?V34 != 3) && (?V31 != 4 || ?V34 != 4) )
		&& 
		( (?V31 != 1 || ?V41 != 1) && (?V31 != 2 || ?V41 != 2) && (?V31 != 3 || ?V41 != 3) && (?V31 != 4 || ?V41 != 4) )
		&& 
		( (?V31 != 1 || ?V42 != 1) && (?V31 != 2 || ?V42 != 2) && (?V31 != 3 || ?V42 != 3) && (?V31 != 4 || ?V42 != 4) )
		&& 
		( (?V32 != 1 || ?V33 != 1) && (?V32 != 2 || ?V33 != 2) && (?V32 != 3 || ?V33 != 3) && (?V32 != 4 || ?V33 != 4) )
		&& 
		( (?V32 != 1 || ?V34 != 1) && (?V32 != 2 || ?V34 != 2) && (?V32 != 3 || ?V34 != 3) && (?V32 != 4 || ?V34 != 4) )
		&& 
		( (?V32 != 1 || ?V42 != 1) && (?V32 != 2 || ?V42 != 2) && (?V32 != 3 || ?V42 != 3) && (?V32 != 4 || ?V42 != 4) )
		&& 
		( (?V32 != 1 || ?V41 != 1) && (?V32 != 2 || ?V41 != 2) && (?V32 != 3 || ?V41 != 3) && (?V32 != 4 || ?V41 != 4) )
		&& 
		( (?V33 != 1 || ?V34 != 1) && (?V33 != 2 || ?V34 != 2) && (?V33 != 3 || ?V34 != 3) && (?V33 != 4 || ?V34 != 4) )
		&& 
		( (?V33 != 1 || ?V43 != 1) && (?V33 != 2 || ?V43 != 2) && (?V33 != 3 || ?V43 != 3) && (?V33 != 4 || ?V43 != 4) )
		&& 
		( (?V33 != 1 || ?V44 != 1) && (?V33 != 2 || ?V44 != 2) && (?V33 != 3 || ?V44 != 3) && (?V33 != 4 || ?V44 != 4) )
		&& 
		( (?V34 != 1 || ?V44 != 1) && (?V34 != 2 || ?V44 != 2) && (?V34 != 3 || ?V44 != 3) && (?V34 != 4 || ?V44 != 4) )
		&& 
		( (?V34 != 1 || ?V43 != 1) && (?V34 != 2 || ?V43 != 2) && (?V34 != 3 || ?V43 != 3) && (?V34 != 4 || ?V43 != 4) )
		&& 
		( (?V41 != 1 || ?V42 != 1) && (?V41 != 2 || ?V42 != 2) && (?V41 != 3 || ?V42 != 3) && (?V41 != 4 || ?V42 != 4) )
		&& 
		( (?V41 != 1 || ?V43 != 1) && (?V41 != 2 || ?V43 != 2) && (?V41 != 3 || ?V43 != 3) && (?V41 != 4 || ?V43 != 4) )
		&& 
		( (?V41 != 1 || ?V44 != 1) && (?V41 != 2 || ?V44 != 2) && (?V41 != 3 || ?V44 != 3) && (?V41 != 4 || ?V44 != 4) )
		&& 
		( (?V42 != 1 || ?V43 != 1) && (?V42 != 2 || ?V43 != 2) && (?V42 != 3 || ?V43 != 3) && (?V42 != 4 || ?V43 != 4) )
		&& 
		( (?V42 != 1 || ?V44 != 1) && (?V42 != 2 || ?V44 != 2) && (?V42 != 3 || ?V44 != 3) && (?V42 != 4 || ?V44 != 4) )
		&& 
		( (?V43 != 1 || ?V44 != 1) && (?V43 != 2 || ?V44 != 2) && (?V43 != 3 || ?V44 != 3) && (?V43 != 4 || ?V44 != 4) )
	)
}