PREFIX : <http://www.w3.org>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?L01 ?L02 ?L03 ?L04 ?L05 ?L06 ?L07 ?L08 ?L09 ?L10 ?L11 ?L12 ?L13 
WHERE {
	:D1 :values ?L01.
	:D1 :values ?L02.
	:D1 :values ?L03.
	:D1 :values ?L04.
	:D1 :values ?L05.
	:D1 :values ?L06.
	:D1 :values ?L07.
	:D1 :values ?L08.
	:D1 :values ?L09.
	:D1 :values ?L10.
	:D1 :values ?L11.
	:D1 :values ?L12.
	:D1 :values ?L13.
	FILTER (
		( (?L01 = 7 && ?L02 = 4 && ?L03 = 13 && ?L04 = 2 && ?L05 = 13) || (?L01 = 9 && ?L02 = 1 && ?L03 = 13 && ?L04 = 2 && ?L05 = 12) || (?L01 = 13 && ?L02 = 7 && ?L03 = 2 && ?L04 = 2 && ?L05 = 14) || (?L01 = 13 && ?L02 = 11 && ?L03 = 1 && ?L04 = 3 && ?L05 = 9) || (?L01 = 13 && ?L02 = 14 && ?L03 = 2 && ?L04 = 2 && ?L05 = 12) )
		&& 
		( (?L03 = 1 && ?L06 = 9 && ?L09 = 13 && ?L12 = 4) || (?L03 = 2 && ?L06 = 1 && ?L09 = 12 && ?L12 = 11) || (?L03 = 7 && ?L06 = 3 && ?L09 = 8 && ?L12 = 2) || (?L03 = 3 && ?L06 = 12 && ?L09 = 4 && ?L12 = 11) || (?L03 = 13 && ?L06 = 1 && ?L09 = 10 && ?L12 = 2) )
		&& 
		( (?L08 = 1 && ?L09 = 9 && ?L10 = 13 && ?L11 = 4) || (?L08 = 2 && ?L09 = 1 && ?L10 = 12 && ?L11 = 11) || (?L08 = 7 && ?L09 = 3 && ?L10 = 8 && ?L11 = 2) || (?L08 = 3 && ?L09 = 12 && ?L10 = 4 && ?L11 = 11) || (?L08 = 13 && ?L09 = 1 && ?L10 = 10 && ?L11 = 2) )
		&& 
		( (?L05 = 9 && ?L07 = 2 && ?L11 = 14) || (?L05 = 12 && ?L07 = 5 && ?L11 = 11) || (?L05 = 13 && ?L07 = 5 && ?L11 = 11) || (?L05 = 14 && ?L07 = 2 && ?L11 = 11) || (?L05 = 15 && ?L07 = 2 && ?L11 = 13) )
		&& 
		( (?L12 = 6 && ?L13 = 2) || (?L12 = 3 && ?L13 = 14) || (?L12 = 11 && ?L13 = 4) || (?L12 = 5 && ?L13 = 14) )
		&& 
		( (?L10 = 6 && ?L13 = 2) || (?L10 = 3 && ?L13 = 14) || (?L10 = 11 && ?L13 = 4) || (?L10 = 5 && ?L13 = 14) )
	)
}